/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE locationBaseService PLEASE EDIT ../location.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { AngularFirestore, AngularFirestoreDocument, AngularFirestoreCollection, DocumentReference } from '@angular/fire/firestore';
import { AngularFireFunctions } from '@angular/fire/functions';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Location } from '../../domain/roomenta_db/location';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../location.service.ts
 */

/*
 * SCHEMA DB location
 *
	{
		name: {
			type: 'String',
			required : true
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		location: {
			type: Schema.ObjectId,
			required : true,
			ref : "room"
		},
	}
 *
 */
@Injectable()
export class LocationBaseService {

    private locationCollection: AngularFirestoreCollection<Location>;
    constructor(
        private afs: AngularFirestore,
        private fns: AngularFireFunctions
    ) {
        this.locationCollection = afs.collection<Location>('location');
    }


    // CRUD METHODS

    /**
    * locationService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Location): Promise<DocumentReference> {
        return this.locationCollection.add(item);
    }

    /**
    * locationService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string) {
        const itemDoc: AngularFirestoreDocument<any> = this.locationCollection.doc(id);
        itemDoc.delete();
    }

    /**
    * locationService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id 
    *
    */
    get(id: string): AngularFirestoreDocument<Location> {
        return this.afs.doc<Location>('location/' + id);
    }

    /**
    * locationService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Location[]> {
        return this.afs.collection('location').snapshotChanges().pipe(
            map(actions => actions.map(a => {
                const data = a.payload.doc.data() as Location;
                const id = a.payload.doc.id;
                return { id, ...data };
            }))
        );
    }

    /**
    * locationService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(itemDoc: AngularFirestoreDocument<Location>, item: Location): Promise<void> {
        return itemDoc.update(item);
    }


    // Custom APIs

}
