/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE roomBaseService PLEASE EDIT ../room.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { AngularFirestore, AngularFirestoreDocument, AngularFirestoreCollection, DocumentReference } from '@angular/fire/firestore';
import { AngularFireFunctions } from '@angular/fire/functions';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Room } from '../../domain/roomenta_db/room';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../room.service.ts
 */

/*
 * SCHEMA DB room
 *
	{
		audio: {
			type: 'Boolean'
		},
		capacity: {
			type: 'Integer',
			required : true
		},
		projector: {
			type: 'Boolean'
		},
		video: {
			type: 'Boolean'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		location: {
			type: Schema.ObjectId,
			required : true,
			ref : "room"
		},
	}
 *
 */
@Injectable()
export class RoomBaseService {

    private roomCollection: AngularFirestoreCollection<Room>;
    constructor(
        private afs: AngularFirestore,
        private fns: AngularFireFunctions
    ) {
        this.roomCollection = afs.collection<Room>('room');
    }


    // CRUD METHODS

    /**
    * roomService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Room): Promise<DocumentReference> {
        return this.roomCollection.add(item);
    }

    /**
    * roomService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string) {
        const itemDoc: AngularFirestoreDocument<any> = this.roomCollection.doc(id);
        itemDoc.delete();
    }

    /**
    * roomService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id 
    *
    */
    get(id: string): AngularFirestoreDocument<Room> {
        return this.afs.doc<Room>('room/' + id);
    }

    /**
    * roomService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Room[]> {
        return this.afs.collection('room').snapshotChanges().pipe(
            map(actions => actions.map(a => {
                const data = a.payload.doc.data() as Room;
                const id = a.payload.doc.id;
                return { id, ...data };
            }))
        );
    }

    /**
    * roomService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(itemDoc: AngularFirestoreDocument<Room>, item: Room): Promise<void> {
        return itemDoc.update(item);
    }


    // Custom APIs

}
